Question delete
gustavoogarcia/gas-form pull request #83
Opened 2021-06-30 19:50 UTC by AndreNunes1812

2021-07-01 21:28 UTC, vyamashiro requested changes

2021-07-01 21:28 UTC, vyamashiro commented on example/package.json
> +    "react-hot-toast": "^2.0.0",
Pq instalou a dependência na pasta example e não na pasta anterior ?

2021-07-01 21:40 UTC, AndreNunes1812 commented
Boa Noite,

Na realidade não atentei  para a pasta existe algum problema ou pode ficar
nessa mesma pasta?


sds

Em qui., 1 de jul. de 2021 às 23:28, Victor Katsuo Yamashiro <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In example/package.json
> <https://github.com/gustavoogarcia/gas-form/pull/83#discussion_r662602480>
> :
>
> > @@ -21,6 +21,7 @@
>
>      "polished": "^4.1.1",
>
>      "react": "link:../node_modules/react",
>
>      "react-dom": "link:../node_modules/react-dom",
>
> +    "react-hot-toast": "^2.0.0",
>
>
> Pq instalou a dependência na pasta example e não na pasta anterior ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gustavoogarcia/gas-form/pull/83#pullrequestreview-697668065>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADS34FAYGHEFDMKLBPQFSGTTVTMXPANCNFSM47TASAAA>
> .
>

2021-07-02 14:44 UTC, vyamashiro approved these changes

2021-07-02 14:44 UTC, merged